### ISSUE TITLE
Migrate from AsyncStorage to MMKV

### ISSUE THREAD

**Issue by DavideSegullo** [nabla-studio/nablajs#25]
We can improve performance by migrating from AsyncStorage to [MMKV](https://github.com/mrousavy/react-native-mmkv)

**Comment by DavideSegullo** [comment]
We should use the new version https://github.com/mrousavy/react-native-mmkv/releases/tag/v2.7.0, so we can use `fastWrites` to avoid storage overflow

**Comment by giorgionocera** [comment]
Nice! Have you checked for any safety side effects?

**Comment by DavideSegullo** [comment]
> Nice! Have you checked for any safety side effects?

Do you mean about memory management and external access to it? All the data are stored inside a key-value storage, each value related to the keyring is encrypted.

I was talking about `fastWrites`:

> 2.7.0 adds a new prop to the MMKV configuration that changes the behaviour of set calls.
> 
> When fastWrites is set to true, MMKV does not overwrite previous values when calling set. This is faster, but uses more memory.
> When fastWrites is set to false, MMKV deletes the previous value before calling set. This makes sure the storage size is always as small as possible, with the added performance cost of one delete call before setting.
> Before this version, MMKV behaved as if fastWrites was set to true (i.e.; fast, but use more memory). Now after this PR, fastWrites is false by default, because users were complaining in https://github.com/mrousavy/react-native-mmkv/issues/440 that the storage size grows too big.

I think we prefer a slower behaviour then a faster one, because memory management can be critical. 

@giorgionocera what do you think?

**Comment by giorgionocera** [comment]
Okay, now it is clear :D
We should use the `fastWrites=false` configuration parameter. I agree with you ;)

**Comment by DavideSegullo** [comment]
A couple of days ago I found out that there was a revert of this [modification](https://github.com/mrousavy/react-native-mmkv/commit/739683a1cf398eee603ee19feeb5e7a3e0a3beec).

Not understanding why, as it was not documented, I asked on [twitter](https://twitter.com/davide_segullo/status/1630935137230766080).

In short, it was a false bug and the change to the source slowed down the code unnecessarily:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/17269969/222535269-7996a0e5-f737-4633-84a4-915fc071d847.png">

So we need to upgrade to a newer version, thus reversing the change proposed in this issue.
